// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARIem4fcQV6X9I67CFfqaCsr2IBSL41Us',
    appId: '1:634366972858:web:9561a089b5e3904d7d0383',
    messagingSenderId: '634366972858',
    projectId: 'timely-32c28',
    authDomain: 'timely-32c28.firebaseapp.com',
    storageBucket: 'timely-32c28.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK8OJ9I7vFICk08BxWnfsvGAWqd1-pQBY',
    appId: '1:634366972858:android:6b59316cdcfb75f07d0383',
    messagingSenderId: '634366972858',
    projectId: 'timely-32c28',
    storageBucket: 'timely-32c28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeb6f68SEtKmPGNmTjw3A1c6guuGUX44Y',
    appId: '1:634366972858:ios:4b3b79d70483c0ac7d0383',
    messagingSenderId: '634366972858',
    projectId: 'timely-32c28',
    storageBucket: 'timely-32c28.appspot.com',
    iosBundleId: 'com.example.timely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeb6f68SEtKmPGNmTjw3A1c6guuGUX44Y',
    appId: '1:634366972858:ios:eb1e12f81a1571db7d0383',
    messagingSenderId: '634366972858',
    projectId: 'timely-32c28',
    storageBucket: 'timely-32c28.appspot.com',
    iosBundleId: 'com.example.timely.RunnerTests',
  );
}
